FROM node:18-alpine  
  
# Instalar xdg-utils para abrir el navegador  
RUN apk add --no-cache xdg-utils  
  
WORKDIR /app  
  
COPY package*.json ./  
  
RUN npm install  
  
COPY . .  
  
EXPOSE 5173  
  
CMD ["npm", "run", "dev"]